#
#                                    i  t
#                                   LE  ED.
#                                  L#E  E#K:
#                                 G#W.  E##W;
#                                D#K.   E#E##t
#                               E#K.    E#t ##f
#                             .E#E.     E#t  ;#D.
#                            .K#E       E#ELLE##K:
#                           .K#D        E#L;;;;;;,
#                          .W#G      .K E#t
#                         :W##########W E#t
#                         :,,,,,,,,,,,, .
#
#
#     Personal alacritty configuration of Luke Petherbridge <me@lukeworks.tech>

general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.70
